#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

#update the package installer
sudo apt-get -y update

#install Nginx
sudo apt-get -y install nginx

#allow http traffic through the firewall
ufw allow 'Nginx HTTP'

# Create default nginx folder for pages
sudo mkdir -p /var/www/html

# Change ownership of file and directories to the current user
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html

#configure nginx default page, print hello world!
echo 'Hello World!' > /var/www/html/index.html-debian.html

#start nginx web server
service nginx start
