#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

#update the package installer
sudo apt update

#install Nginx
sudo apt install -y nginx

#configure Nginx to listen to port 80
# sudo bash -c "echo server {
#     listen 80;
#     server_name web_01;

#     location \ {
#         echo -e \"HTTP/1.1 200 OK\\r\\n\\r\\Hello World!\";
#     }
# }" > /var/www/html/index.html

echo 'Hello World!' > /var/www/html/index.html

#test nginx config
sudo nginx -t

#restart nginx(without systemctl)
sudo /etc/innit.d/nginx restart

