#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "53s/.*/location \/redirect_me {\n\treturn 301 http:\/\/github.com\/\;\n}/" /etc/nginx/sites-available/default
sudo service nginx start
