#!/usr/bin/env bash
# installs nginx server

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
