#!/usr/bin/env bash
#installs nginx server

# Update
apt-get -y update
apt-get -y upgrade

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
# HAProxy configuration to haproxy.cfg

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 172082-web-01 34.232.72.158:80 check
    server 172082-web-02 34.224.83.81:80 check
"

# Start the HAProxy service
sudo service haproxy start
