#!/usr/bin/env bash
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/mycript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

myfile = /var/run/myscript.pid

terminator() {
  rm myfile
  exit
}

echo "$$" > myfile

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
