#!/usr/bin/env bash
# kills the infinity and beyond  program using sigkill signal

# kill "$(pgrep -f 4-to_infinity_and_beyond)"

# Get the pid of "4-to_infinity_and_beyond" process
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Send termination signal to the process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
