#!/usr/bin/env bash
#Bash script to handle the sigterm signal

handle_sigterm(){
	echo "I am invincible!"
}
#register the sigterm signal handler

trap handle_sigterm

#print the message to infinity
while true
do
	echo "To infinity and beyond"
	sleep 2
done
