#!/usr/bin/env bash
#display time for 12hrs 59min(hr from 0-12) (min from 1-59)

hours=0

while [ $hours -lt 12 ]
do
    echo "Hour: $hours"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( hours++ ))
done
